version: "2"
services:
  janus:
    image: quay.io/hellofresh/janus
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - svc-item
      - svc-price
    volumes:
      - ./janus.toml:/etc/janus/janus.toml
      - ./apis:/etc/janus/apis
    networks:
      - docker_item

#  svc-aggregator:
#    build:
#      context: ../src/svc-aggregator
#    image: go-svc-aggregator
#    container_name: item-aggregator
#    networks:
#      - docker_item
#    ports:
#      - 10000:10000

  svc-item:
    build:
      context: ../src/svc-item
    image: go-svc-item
    container_name: svc-item
    networks:
      - docker_item
    ports:
      - 10001:10001

  svc-price:
    build:
      context: ../src/svc-price
    image: go-svc-price
    container_name: svc-price
    networks:
      - docker_item
    ports:
      - 10002:10002

networks:
  docker_item:
    external: true